version: '3'
services:
  web:
    container_name: web
    image: json-formatter_web
    volumes:
      - //json-formatter:/app
      - /app/node_modules
    ports:
      - "3030:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true